/**:
    ros__parameters:
        n_aruco_ids: 120
        aruco_size: 0.2 # meters
        camera_model: "pinhole"
        camera_qos_reliable: true
        goal_id: 75
        camera_frame: "camera_link"
        ref_frame: "drone0/base_link"
        max_distance: 10.0
        n_first_samples: 5
